#ifndef __PARTITIONERREURS_H__
#define __PARTITIONERREURS_H__

#define TABLEPART_ERREUR_OK         0
#define TABLEPART_ERREUR_TAILLE_SUPPERIEUR_TAILLE_MAX_PARTITION   1
#define TABLEPART_ERREUR_PLUS_DE_PARTITION_DISPONIBNLE            2
#define TABLEPART_ERREUR_ESPACE_INSUFFISANT_OU_FRAGMENTE          3
#define TABLEPART_ERREUR_ESPACE_INSUFFISANT_APRES_PARTITION       4


#define TABLEPART_ERREUR_ERREUR_ARGUMENT                          0xFF

#define TABLEPART_ERREUR16_


#endif
